SELECT *
FROM Customer

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerName = 'Alex'
ROLLBACK

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerPhone = '123123123'
COMMIT

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerAddres = 'Jalan Utara 80'
COMMIT