CREATE DATABASE eCommerce

CREATE TABLE ItemType(
	ItemTypeID CHAR(5) NOT NULL,
	ItemTypeName VARCHAR(50) NOT NULL,
	Primary key (ItemTypeID),
	CONSTRAINT CekTypeID CHECK (ItemTypeID LIKE 'IT[0-9][0-9][0-9]')
)
DROP TABLE ItemType
CREATE TABLE Item(
	ItemID CHAR(5) NOT NULL,
	CONSTRAINT CekItemID CHECK (ItemID LIKE 'IM[0-9][0-9][0-9]'),
	PRIMARY KEY(ItemID),

	ItemTypeID CHAR(5) REFERENCES ItemType ON UPDATE CASCADE ON DELETE CASCADE,
	ItemName VARCHAR(15) NOT NULL,
	Price NUMERIC(11,2),
	Quantity INT
)
DROP TABLE Item
CREATE TABLE HeaderSellTransaction(
	TransactionID CHAR(5) NOT NULL,
	PRIMARY KEY (TransactionID),
	CONSTRAINT CekTransactionID CHECK (TransactionID LIKE 'TR[0-9][0-9][0-9]'),

	CustomerID CHAR(50) NOT NULL REFERENCES Customer ON UPDATE CASCADE ON DELETE CASCADE,
	StaffID CHAR(5) REFERENCES Staff ON UPDATE CASCADE ON DELETE CASCADE,
	TransactionDate DATE,
	PaymentType VARCHAR(20),
)
DROP TABLE HeaderSellTransaction
CREATE TABLE DetailSellTransaction(
	TransactionID CHAR(5) REFERENCES HeaderSellTransaction ON UPDATE CASCADE ON DELETE CASCADE,
	ItemID CHAR(5) REFERENCES Item ON UPDATE CASCADE ON DELETE CASCADE,
	SellQuantity INT
)
DROP TABLE DetailSellTransaction